### ISSUE TITLE
Directory Structure Only.

### ISSUE THREAD

**Issue by thomcomstock** [mon/bigDecrypter#2]
After correctly using this program for FXG.big, the resultant file 'FXG_decrypted.big' was empty of content except for the directory structure. Please advise.

**Comment by mon** [comment]
Gearbox stopped encrypting the .big files many years ago, sometime around 2018.
Unless you have explicitly downloaded the old depot files, then this tool is not required. Please extract as normal.
Thanks!

**Comment by thomcomstock** [comment]
Thank you for your prompt response.

Apparently, the FX crew has begun encrypting their own files. They have, as well made the files themselves unreadable when extracted. I have never understood the need for Mod creators to proprietorize their creations, but they sometimes do. As a scientist (astrophysics et.al.) I applaud those who, like yourself, choose to publish opensource, sharing their data, processes and methods.

Thom Comstock

"None are so hopelessly enslaved as those who falsely believe they are free."
~ Johann Wolfgang von Goethe    

    On Thursday, January 6, 2022, 04:42:54 AM EST, Will ***@***.***> wrote:  
 
 


Gearbox stopped encrypting the .big files many years ago, sometime around 2018.
Unless you have explicitly downloaded the old depot files, then this tool is not required. Please extract as normal.
Thanks!

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mon** [comment]
Oh, that is quite interesting! So the decrypter actually generates a valid output .big and doesn't print any errors? Then they are definitely being cheeky and encrypting it using gearbox's old methods.

I wonder if the unencrypted file has been intentionally tampered with to break standard extractors - I'm sure the data is in there.
Unfortunately the main decryption is the easy part, and .big files themselves are a little complex, so I can't help diagnose what they've done to it.

**Comment by thomcomstock** [comment]
The stange part is that each of the files within the directories have a (seemingly correct) size to them, but when I open them in TextPad, they appear blank as though they were using a white font on a white background. I do not know enough about encoding to imagine how they have accomplished that, but there does seem to be a 'volume' to the files as they register in Windows Explorer.

Thom Comstock

"None are so hopelessly enslaved as those who falsely believe they are free."
~ Johann Wolfgang von Goethe    

    On Thursday, January 6, 2022, 09:07:23 PM EST, Will ***@***.***> wrote:  
 
 


Oh, that is quite interesting! So the decrypter actually generates a valid output .big and doesn't print any errors? Then they are definitely being cheeky and encrypting it using gearbox's old methods.

I wonder if the unencrypted file has been intentionally tampered with to break standard extractors - I'm sure the data is in there.
Unfortunately the main decryption is the easy part, and .big files themselves are a little complex, so I can't help diagnose what they've done to it.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mon** [comment]
Hmmm - a lot of files inside a .big are actually binary files. Have you looked at other .big files before and know what to expect? You may want to download a hex editor (such as HxD) to inspect them more clearly.

**Comment by thomcomstock** [comment]
As an aside: I have a huge collection of just about every HW2 and HWRM mod, tool, tutorial, sound-file, texture, model and map-pack created since 1999 as well as many spidered and now defunct websites (including the original Relic Forums, Karos Graveyard, hw2wiki.net and the HWModdingWiki) and most if not all of the original HW2 concept art. Although there is some redundancy to my collection, it amounts to some 269GB consisting of 534,979 Files in 116,052 Directories (Folders). Note: Anyone interested is welcome to any or all of it. 

That having been said, I am not as familiar with binary or hexadecimal files as perhaps I should be and have never really paid them much attention except as a time-consuming irritant. What kind of number are we speaking of in HW2?

Thom Comstock

"None are so hopelessly enslaved as those who falsely believe they are free."
~ Johann Wolfgang von Goethe    

    On Friday, January 7, 2022, 08:00:11 PM EST, Will ***@***.***> wrote:  
 
 


Hmmm - a lot of files inside a .big are actually binary files. Have you looked at other .big files before and know what to expect? You may want to download a hex editor (such as HxD) to inspect them more clearly.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lone-wolf-akela** [comment]
I'm one of the creators of FX:Galaxy mod.

Those encrypted .big files are created with [LoneWolf_Archiver ](https://github.com/lone-wolf-akela/LoneWolf_Archiver), which are intentionally tampered to not be extracted by bigDecrypter. 

> As a scientist (astrophysics et.al.) I applaud those who, like yourself, choose to publish opensource, sharing their data, processes and methods.

As a electronic engineer myself, I do also like the ideas of open and sharing. But since the FX Mod project is something that is almost 19 years old, many different people have taken part in the development of the mod. Some of those developers really don't like unauthorized uses of their creation, so we (as a team) still encrypt our files.

I see that Thom has already starred the [FX_Galaxy_OS ](https://github.com/9CCN-MOD-Team/FX_Galaxy_OS) repo; that repo has provided things that we as a team have agreed to publish to the public. If you really want to get access to other things like our 3D models for personal use, you may email me or the team(homeworld_9ccn@163.com) and tell us which file you are interested in, and we can help you to get in touch with the specific creator of that file/model and ask his/her permission.

**Comment by mon** [comment]
> Those encrypted .big files are created with LoneWolf_Archiver , which are intentionally tampered to not be extracted by bigDecrypter

See now we have a legitimate .big that I can't handle. You've just activated my trap card.

**Comment by mon** [comment]
v1.5 has been released, which correctly decrypts FXG.big.

Both LoneWolf_Archiver and Archive.exe cannot extract the resulting .big because of a deliberately malformed file, "[]don't ever try to extract me" (lol nice try). It is invalidly compressed.

Archive.exe from my currently installed Steam version of "Homeworld Remastered Toolkit" is trivially patched to allow extraction. Grab that hex editor I recommended (HxD) and change the bytes at these offsets:
Offset 122FA: 74 -> EB
Offset 1433D: 74 -> EB

Extraction will succeed.

**Comment by thomcomstock** [comment]
Drag&Drop = Program can't start because msys-2.0.dll is missing.

Thom Comstock

"None are so hopelessly enslaved as those who falsely believe they are free."
~ Johann Wolfgang von Goethe    

    On Saturday, January 8, 2022, 09:49:10 AM EST, Will ***@***.***> wrote:  
 
 


Closed #2.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mon** [comment]
Classic msys life. Have rebuilt using mingw and it should work now.

**Comment by thomcomstock** [comment]
Just a note about the hex modifications you mentioned: I did download HxD, but then I realized that I was out of my depth here when I had no idea which file you were suggesting I modify... your own decrypter, Archive.exe or the bigfile itself. 

Thom Comstock


    On Saturday, January 8, 2022, 09:49:10 AM EST, Will ***@***.***> wrote:  
 
 


v1.5 has been released, which correctly decrypts FXG.big.

Both LoneWolf_Archiver and Archive.exe cannot extract the resulting .big because of a deliberately malformed file, "[]don't ever try to extract me" (lol nice try). It is invalidly compressed.

Archive.exe from my currently installed Steam version of "Homeworld Remastered Toolkit" is trivially patched to allow extraction. Grab that hex editor I recommended (HxD) and change the bytes at these offsets:
Offset 122FA: 74 -> EB
Offset 1433D: 74 -> EB

Extraction will succeed.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by thomcomstock** [comment]
Very interesting. Did you test it? I first checked the ship directory to see the changes and all of the contents of each ship's folder is different than the folder's title. The files throughout the entire mod seem to have been randomly shifted into other folders.

As well, they compiled every lua file and none of the hod files are easily openable (I tried everything... Spooky's Hod Tool, 9 versions of CFHodEd [2.8.5 - 4.2] and CFHodEdRM 2.0). I have not yet tried Maya.

I guess they are quite serious about keeping their secrets.

The amount of work you have done is quite remarkable. I guess, like myself you enjoy challenges. 

Thom Comstock

"None are so hopelessly enslaved as those who falsely believe they are free."
~ Johann Wolfgang von Goethe    

    On Saturday, January 8, 2022, 08:35:49 PM EST, Will ***@***.***> wrote:  
 
 


Classic msys life. Have rebuilt using mingw and it should work now.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mon** [comment]
bigDecrypter holds a special place in my life as the first reverse engineering task I was actually successful with, which is why this was close to home ^_^

I took the valid (albiet compiled) nature of the lua files as proof there was no more work to do - I suspect if the folder organisation is weird, that's just how the source repository has been laid out. Doesn't the HWRM kit on steam have a HOD extractor as well? I vaguely recall the format changing a fair amount.

As a complete aside - whatever email client you're using, github isn't properly detecting where your reply ends and the quote of the previous message begins. It might be worth deleting the quoted message just to clean up replies a little 👍

**Comment by lone-wolf-akela** [comment]
> all of the contents of each ship's folder is different than the folder's title. The files throughout the entire mod seem to have been randomly shifted into other folders.

That's not intentional. There must be something wrong.

**Comment by thomcomstock** [comment]
I'll just reply from within github from now on.

What I meant about the folder organization was that, for example: 

Looking within data:ship/ben_bentus/ I find...
hgn_battlecruiserelite.events
hgn_battlecruiserelite.hod
hgn_battlecruiserelite.ship 

within data:ship/ben_bentusiexchange/ I find...
tai_multiguncorvette.ship

within data:ship/ben_cargobarge/ I find...
vgr_defensecruiser1.events
vgr_defensecruiser1.hod
vgr_defensecruiser1.ship

Every folder in the entire mod (not just ship, but every single folder) is like this except that at least in the ship folder they are all ship files. The other folders are far more disorganized - familylist.lua and flightmaneuvers.lua in data:art/fx/ etc.
